### ISSUE TITLE
wrong method used for SMOTE

### ISSUE THREAD

**Issue by zshoorbajee** [learn-co-curriculum/dsc-class-imbalance-problems-lab#1]
## Link to Canvas

https://learning.flatironschool.com/courses/4958/assignments/170723?module_item_id=371424

## Issue Subtype

- [ ] Master branch code
- [x] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
# Previous original class distribution
print(y.value_counts()) 
X_resampled, y_resampled = SMOTE().fit_sample(X, y) 
```

### Concern

SMOTE does not have a method called .fit_sample. It's supposed to be fit_resample.

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by hoffm386** [comment]
Thanks for flagging, @zshoorbajee 

Looks like the `fit_sample` alias was removed in a recent update to the imbalanced-learn package. This has been fixed in https://github.com/learn-co-curriculum/dsc-class-imbalance-problems-lab/pull/4
