### ISSUE TITLE
Smote has no attribute fit_sample

### ISSUE THREAD

**Issue by Davidkeebler** [learn-co-curriculum/dsc-class-imbalance-problems-lab#5]
## Link to Canvas

https://learning.flatironschool.com/courses/6485/assignments/241684?module_item_id=568283

## Issue Subtype

- [x ] Master branch code
- [x ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
X_resampled, y_resampled = SMOTE().fit_sample(X, y) 
```

### Concern

SMOTE has no attribute fit_sample. The correct attribute is fit_resample. This attribute is correctly used earlier in the lesson but not here.

## (Optional) Proposed Solution

The code works perfectly if it uses the fit_resample method instead.
```
X_resampled, y_resampled = SMOTE().fit_resample(X, y) 
```

## What OS Are You Using?

- [ ] OS X
- [x ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for raising this issue. We're taking a look.

**Comment by bpurdy-ds** [comment]
Fixed. It was correct in the solution branch, but not curriculum branch. Thanks for noticing.
